
export const provincias = [
  { id: "1", nombre: "San José", iso: "SJ" },
  { id: "2", nombre: "Alajuela", iso: "A" },
  { id: "3", nombre: "Cartago", iso: "C" },
  { id: "4", nombre: "Heredia", iso: "H" },
  { id: "5", nombre: "Guanacaste", iso: "G" },
  { id: "6", nombre: "Puntarenas", iso: "P" },
  { id: "7", nombre: "Limón", iso: "L" },
];

export const cantones = {
  // ========== PROVINCIA DE SAN JOSÉ (1) ==========
  "1": [
    {
      nombre: "San José",
      codigoPostal: "10101",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Carmen" },
        { nombre: "Merced" },
        { nombre: "Hospital" },
        { nombre: "Catedral" },
        { nombre: "Zapote" },
        { nombre: "San Francisco de Dos Ríos" },
        { nombre: "Uruca" },
        { nombre: "Mata Redonda" },
        { nombre: "Pavas" },
        { nombre: "Hatillo" },
        { nombre: "San Sebastián" },
      ],
    },
    {
      nombre: "Escazú",
      codigoPostal: "10201",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Escazú" },
        { nombre: "San Antonio" },
        { nombre: "San Rafael" },
      ],
    },
    {
      nombre: "Desamparados",
      codigoPostal: "10301",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Desamparados" },
        { nombre: "San Miguel" },
        { nombre: "San Juan de Dios" },
        { nombre: "San Rafael Arriba" },
        { nombre: "San Antonio" },
        { nombre: "Frailes" },
        { nombre: "Patarrá" },
        { nombre: "San Cristóbal" },
        { nombre: "Rosario" },
        { nombre: "Damas" },
        { nombre: "San Rafael Abajo" },
        { nombre: "Gravilias" },
        { nombre: "Los Guido" },
      ],
    },
    {
      nombre: "Puriscal",
      codigoPostal: "10401",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Santiago" },
        { nombre: "Mercedes Sur" },
        { nombre: "Barbacoas" },
        { nombre: "Grifo Alto" },
        { nombre: "San Rafael" },
        { nombre: "Candelarita" },
        { nombre: "Desamparaditos" },
        { nombre: "San Antonio" },
        { nombre: "Chires" },
      ],
    },
    {
      nombre: "Tarrazú",
      codigoPostal: "10501",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Marcos" },
        { nombre: "San Lorenzo" },
        { nombre: "San Carlos" },
      ],
    },
    {
      nombre: "Aserrí",
      codigoPostal: "10601",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Aserrí" },
        { nombre: "Tarbaca" },
        { nombre: "Vuelta de Jorco" },
        { nombre: "San Gabriel" },
        { nombre: "Legua" },
        { nombre: "Monterrey" },
        { nombre: "Salitrillos" },
      ],
    },
    {
      nombre: "Mora",
      codigoPostal: "10701",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Colón" },
        { nombre: "Guayabo" },
        { nombre: "Tabarcia" },
        { nombre: "Piedras Negras" },
        { nombre: "Picagres" },
        { nombre: "Jaris" },
      ],
    },
    {
      nombre: "Goicoechea",
      codigoPostal: "10801",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Guadalupe" },
        { nombre: "Caldera" },
        { nombre: "Purral" },
        { nombre: "Ipís" },
        { nombre: "Rancho Redondo" },
        { nombre: "Mata de Plátano" },
      ],
    },
    {
      nombre: "Santa Ana",
      codigoPostal: "10901",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Santa Ana" },
        { nombre: "Salitral" },
        { nombre: "Pozos" },
        { nombre: "Uruca" },
        { nombre: "Piedades" },
        { nombre: "Brasil" },
      ],
    },
    {
      nombre: "Alajuelita",
      codigoPostal: "11001",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Alajuelita" },
        { nombre: "San Josecito" },
        { nombre: "San Antonio" },
        { nombre: "Concepción" },
        { nombre: "San Felipe" },
      ],
    },
    {
      nombre: "Vázquez de Coronado",
      codigoPostal: "11101",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Isidro" },
        { nombre: "San Rafael" },
        { nombre: "Dulce Nombre de Jesús" },
        { nombre: "Patalillo" },
        { nombre: "Cascajal" },
      ],
    },
    {
      nombre: "Acosta",
      codigoPostal: "11201",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Ignacio" },
        { nombre: "Guaitil" },
        { nombre: "Palmichal" },
        { nombre: "Cangrejal" },
        { nombre: "Sabanillas" },
      ],
    },
    {
      nombre: "Tibás",
      codigoPostal: "11301",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Juan" },
        { nombre: "Cinco Esquinas" },
        { nombre: "Anselmo Llorente" },
        { nombre: "León XIII" },
        { nombre: "Colima" },
      ],
    },
    {
      nombre: "Moravia",
      codigoPostal: "11401",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Vicente" },
        { nombre: "San Jerónimo" },
        { nombre: "La Trinidad" },
      ],
    },
    {
      nombre: "Montes de Oca",
      codigoPostal: "11501",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Pedro" },
        { nombre: "Sabanilla" },
        { nombre: "Mercedes" },
        { nombre: "San Rafael" },
      ],
    },
    {
      nombre: "Turrubares",
      codigoPostal: "11601",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Pablo" },
        { nombre: "San Pedro" },
        { nombre: "San Juan de Mata" },
        { nombre: "San Luis" },
        { nombre: "Carara" },
      ],
    },
    {
      nombre: "Dota",
      codigoPostal: "11701",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Santa María" },
        { nombre: "Jardín" },
        { nombre: "Copey" },
      ],
    },
    {
      nombre: "Curridabat",
      codigoPostal: "11801",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Curridabat" },
        { nombre: "Granadilla" },
        { nombre: "Sánchez" },
        { nombre: "Tirrases" },
      ],
    },
    {
      nombre: "Pérez Zeledón",
      codigoPostal: "11901",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Isidro de El General" },
        { nombre: "General" },
        { nombre: "Daniel Flores" },
        { nombre: "Rivas" },
        { nombre: "San Pedro" },
        { nombre: "Platanares" },
        { nombre: "Pejibaye" },
        { nombre: "Cajón" },
        { nombre: "Barú" },
        { nombre: "Río Nuevo" },
        { nombre: "Páramo" },
      ],
    },
    {
      nombre: "León Cortés",
      codigoPostal: "12001",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Pablo" },
        { nombre: "San Andrés" },
        { nombre: "Llano Bonito" },
        { nombre: "San Isidro" },
        { nombre: "Santa Cruz" },
        { nombre: "San Antonio" },
      ],
    },
  ],

  // ========== PROVINCIA DE ALAJUELA (2) ==========
  "2": [
    {
      nombre: "Alajuela",
      codigoPostal: "20101",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Alajuela" },
        { nombre: "San José" },
        { nombre: "Carrizal" },
        { nombre: "San Antonio" },
        { nombre: "Guácima" },
        { nombre: "San Isidro" },
        { nombre: "Sabanilla" },
        { nombre: "San Rafael" },
        { nombre: "Río Segundo" },
        { nombre: "Desamparados" },
        { nombre: "Turrúcares" },
        { nombre: "Tambor" },
        { nombre: "Garita" },
        { nombre: "Sarapiquí" },
      ],
    },
    {
      nombre: "San Ramón",
      codigoPostal: "20201",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Ramón" },
        { nombre: "Santiago" },
        { nombre: "San Juan" },
        { nombre: "Piedades Norte" },
        { nombre: "Piedades Sur" },
        { nombre: "San Rafael" },
        { nombre: "San Isidro" },
        { nombre: "Ángeles" },
        { nombre: "Alfaro" },
        { nombre: "Volio" },
        { nombre: "Concepción" },
        { nombre: "Zapotal" },
        { nombre: "Peñas Blancas" },
      ],
    },
    {
      nombre: "Grecia",
      codigoPostal: "20301",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Grecia" },
        { nombre: "San Isidro" },
        { nombre: "San José" },
        { nombre: "San Roque" },
        { nombre: "Tacares" },
        { nombre: "Puente Piedra" },
        { nombre: "Bolívar" },
      ],
    },
    {
      nombre: "San Mateo",
      codigoPostal: "20401",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Mateo" },
        { nombre: "Desmonte" },
        { nombre: "Jesús María" },
      ],
    },
    {
      nombre: "Atenas",
      codigoPostal: "20501",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Atenas" },
        { nombre: "Jesús" },
        { nombre: "Mercedes" },
        { nombre: "San Isidro" },
        { nombre: "Concepción" },
        { nombre: "San José" },
        { nombre: "Santa Eulalia" },
        { nombre: "Escobal" },
      ],
    },
    {
      nombre: "Naranjo",
      codigoPostal: "20601",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Naranjo" },
        { nombre: "San Miguel" },
        { nombre: "San José" },
        { nombre: "Cirrí Sur" },
        { nombre: "San Jerónimo" },
        { nombre: "San Juan" },
        { nombre: "El Rosario" },
        { nombre: "Palmitos" },
      ],
    },
    {
      nombre: "Palmares",
      codigoPostal: "20701",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Palmares" },
        { nombre: "Zaragoza" },
        { nombre: "Buenos Aires" },
        { nombre: "Santiago" },
        { nombre: "Candelaria" },
        { nombre: "Esquipulas" },
        { nombre: "La Granja" },
      ],
    },
    {
      nombre: "Poás",
      codigoPostal: "20801",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Pedro" },
        { nombre: "San Juan" },
        { nombre: "San Rafael" },
        { nombre: "Carrillos" },
        { nombre: "Sabana Redonda" },
      ],
    },
    {
      nombre: "Orotina",
      codigoPostal: "20901",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Orotina" },
        { nombre: "Mastate" },
        { nombre: "Hacienda Vieja" },
        { nombre: "Coyolar" },
        { nombre: "La Ceiba" },
      ],
    },
    {
      nombre: "San Carlos",
      codigoPostal: "21001",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Quesada" },
        { nombre: "Florencia" },
        { nombre: "Buenavista" },
        { nombre: "Aguas Zarcas" },
        { nombre: "Venecia" },
        { nombre: "Pital" },
        { nombre: "Fortuna" },
        { nombre: "Tigra" },
        { nombre: "Palmera" },
        { nombre: "Venado" },
        { nombre: "Cutris" },
        { nombre: "Monterrey" },
        { nombre: "Pocosol" },
      ],
    },
    {
      nombre: "Zarcero",
      codigoPostal: "21101",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Zarcero" },
        { nombre: "Laguna" },
        { nombre: "Tapesco" },
        { nombre: "Guadalupe" },
        { nombre: "Palmira" },
        { nombre: "Zapote" },
        { nombre: "Brisas" },
      ],
    },
    {
      nombre: "Sarchí",
      codigoPostal: "21201",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Sarchí Norte" },
        { nombre: "Sarchí Sur" },
        { nombre: "Toro Amarillo" },
        { nombre: "San Pedro" },
        { nombre: "Rodríguez" },
      ],
    },
    {
      nombre: "Upala",
      codigoPostal: "21301",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Upala" },
        { nombre: "Aguas Claras" },
        { nombre: "San José" },
        { nombre: "Bijagua" },
        { nombre: "Delicias" },
        { nombre: "Dos Ríos" },
        { nombre: "Yolillal" },
      ],
    },
    {
      nombre: "Los Chiles",
      codigoPostal: "21401",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Los Chiles" },
        { nombre: "Caño Negro" },
        { nombre: "El Amparo" },
        { nombre: "San Jorge" },
      ],
    },
    {
      nombre: "Guatuso",
      codigoPostal: "21501",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Rafael" },
        { nombre: "Buenavista" },
        { nombre: "Cote" },
        { nombre: "Katira" },
      ],
    },
  ],

  // ========== PROVINCIA DE CARTAGO (3) ==========
  "3": [
    {
      nombre: "Cartago",
      codigoPostal: "30101",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Oriental" },
        { nombre: "Occidental" },
        { nombre: "Carmen" },
        { nombre: "San Nicolás" },
        { nombre: "Aguacaliente" },
        { nombre: "Guadalupe" },
        { nombre: "Corralillo" },
        { nombre: "Tierra Blanca" },
        { nombre: "Dulce Nombre" },
        { nombre: "Llano Grande" },
        { nombre: "Quebradilla" },
      ],
    },
    {
      nombre: "Paraíso",
      codigoPostal: "30201",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Paraíso" },
        { nombre: "Santiago" },
        { nombre: "Orosi" },
        { nombre: "Cachí" },
        { nombre: "Llanos de Santa Lucía" },
      ],
    },
    {
      nombre: "La Unión",
      codigoPostal: "30301",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Tres Ríos" },
        { nombre: "San Diego" },
        { nombre: "San Juan" },
        { nombre: "San Rafael" },
        { nombre: "Concepción" },
        { nombre: "Dulce Nombre" },
        { nombre: "San Ramón" },
        { nombre: "Río Azul" },
      ],
    },
    {
      nombre: "Jiménez",
      codigoPostal: "30401",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Juan Viñas" },
        { nombre: "Tucurrique" },
        { nombre: "Pejibaye" },
      ],
    },
    {
      nombre: "Turrialba",
      codigoPostal: "30501",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Turrialba" },
        { nombre: "La Suiza" },
        { nombre: "Peralta" },
        { nombre: "Santa Cruz" },
        { nombre: "Santa Teresita" },
        { nombre: "Pavones" },
        { nombre: "Tuis" },
        { nombre: "Tayutic" },
        { nombre: "Santa Rosa" },
        { nombre: "Tres Equis" },
        { nombre: "La Isabel" },
        { nombre: "Chirripó" },
      ],
    },
    {
      nombre: "Alvarado",
      codigoPostal: "30601",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Pacayas" },
        { nombre: "Cervantes" },
        { nombre: "Capellades" },
      ],
    },
    {
      nombre: "Oreamuno",
      codigoPostal: "30701",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Rafael" },
        { nombre: "Cot" },
        { nombre: "Potrero Cerrado" },
        { nombre: "Cipreses" },
        { nombre: "Santa Rosa" },
      ],
    },
    {
      nombre: "El Guarco",
      codigoPostal: "30801",
      costoEnvio: 2000,
      distritos: [
        { nombre: "El Tejar" },
        { nombre: "San Isidro" },
        { nombre: "Tobosi" },
        { nombre: "Patio de Agua" },
      ],
    },
  ],

  // ========== PROVINCIA DE HEREDIA (4) ==========
  "4": [
    {
      nombre: "Heredia",
      codigoPostal: "40101",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Heredia" },
        { nombre: "Mercedes" },
        { nombre: "San Francisco" },
        { nombre: "Ulloa" },
        { nombre: "Varablanca" },
      ],
    },
    {
      nombre: "Barva",
      codigoPostal: "40201",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Barva" },
        { nombre: "San Pedro" },
        { nombre: "San Pablo" },
        { nombre: "San Roque" },
        { nombre: "Santa Lucía" },
        { nombre: "San José de la Montaña" },
      ],
    },
    {
      nombre: "Santo Domingo",
      codigoPostal: "40301",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Santo Domingo" },
        { nombre: "San Vicente" },
        { nombre: "San Miguel" },
        { nombre: "Paracito" },
        { nombre: "Santo Tomás" },
        { nombre: "Santa Rosa" },
        { nombre: "Tures" },
        { nombre: "Pará" },
      ],
    },
    {
      nombre: "Santa Bárbara",
      codigoPostal: "40401",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Santa Bárbara" },
        { nombre: "San Pedro" },
        { nombre: "San Juan" },
        { nombre: "Jesús" },
        { nombre: "Santo Domingo" },
        { nombre: "Puraba" },
      ],
    },
    {
      nombre: "San Rafael",
      codigoPostal: "40501",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Rafael" },
        { nombre: "San Josecito" },
        { nombre: "Santiago" },
        { nombre: "Ángeles" },
        { nombre: "Concepción" },
      ],
    },
    {
      nombre: "San Isidro",
      codigoPostal: "40601",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Isidro" },
        { nombre: "San José" },
        { nombre: "Concepción" },
        { nombre: "San Francisco" },
      ],
    },
    {
      nombre: "Belén",
      codigoPostal: "40701",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Antonio" },
        { nombre: "La Ribera" },
        { nombre: "La Asunción" },
      ],
    },
    {
      nombre: "Flores",
      codigoPostal: "40801",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Joaquín" },
        { nombre: "Barrantes" },
        { nombre: "Llorente" },
      ],
    },
    {
      nombre: "San Pablo",
      codigoPostal: "40901",
      costoEnvio: 2000,
      distritos: [
        { nombre: "San Pablo" },
        { nombre: "Rincón de Sabanilla" },
      ],
    },
    {
      nombre: "Sarapiquí",
      codigoPostal: "41001",
      costoEnvio: 2000,
      distritos: [
        { nombre: "Puerto Viejo" },
        { nombre: "La Virgen" },
        { nombre: "Horquetas" },
        { nombre: "Llanuras del Gaspar" },
        { nombre: "Cureña" },
      ],
    },
  ],

  // ========== PROVINCIA DE GUANACASTE (5) ==========
  "5": [
    {
      nombre: "Liberia",
      codigoPostal: "50101",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Liberia" },
        { nombre: "Cañas Dulces" },
        { nombre: "Mayorga" },
        { nombre: "Nacascolo" },
        { nombre: "Curubandé" },
      ],
    },
    {
      nombre: "Nicoya",
      codigoPostal: "50201",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Nicoya" },
        { nombre: "Mansión" },
        { nombre: "San Antonio" },
        { nombre: "Quebrada Honda" },
        { nombre: "Sámara" },
        { nombre: "Nosara" },
        { nombre: "Belén de Nosarita" },
      ],
    },
    {
      nombre: "Santa Cruz",
      codigoPostal: "50301",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Santa Cruz" },
        { nombre: "Bolsón" },
        { nombre: "Veintisiete de Abril" },
        { nombre: "Tempate" },
        { nombre: "Cartagena" },
        { nombre: "Cuajiniquil" },
        { nombre: "Diriá" },
        { nombre: "Cabo Velas" },
        { nombre: "Tamarindo" },
      ],
    },
    {
      nombre: "Bagaces",
      codigoPostal: "50401",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Bagaces" },
        { nombre: "Fortuna" },
        { nombre: "Mogote" },
        { nombre: "Río Naranjo" },
      ],
    },
    {
      nombre: "Carrillo",
      codigoPostal: "50501",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Filadelfia" },
        { nombre: "Palmira" },
        { nombre: "Sardinal" },
        { nombre: "Belén" },
      ],
    },
    {
      nombre: "Cañas",
      codigoPostal: "50601",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Cañas" },
        { nombre: "Palmira" },
        { nombre: "San Miguel" },
        { nombre: "Bebedero" },
        { nombre: "Porozal" },
      ],
    },
    {
      nombre: "Abangares",
      codigoPostal: "50701",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Las Juntas" },
        { nombre: "Sierra" },
        { nombre: "San Juan" },
        { nombre: "Colorado" },
      ],
    },
    {
      nombre: "Tilarán",
      codigoPostal: "50801",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Tilarán" },
        { nombre: "Quebrada Grande" },
        { nombre: "Tronadora" },
        { nombre: "Santa Rosa" },
        { nombre: "Líbano" },
        { nombre: "Tierras Morenas" },
        { nombre: "Arenal" },
      ],
    },
    {
      nombre: "Nandayure",
      codigoPostal: "50901",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Carmona" },
        { nombre: "Santa Rita" },
        { nombre: "Zapotal" },
        { nombre: "San Pablo" },
        { nombre: "Porvenir" },
        { nombre: "Bejuco" },
      ],
    },
    {
      nombre: "La Cruz",
      codigoPostal: "51001",
      costoEnvio: 2500,
      distritos: [
        { nombre: "La Cruz" },
        { nombre: "Santa Cecilia" },
        { nombre: "Garita" },
        { nombre: "Santa Elena" },
      ],
    },
    {
      nombre: "Hojancha",
      codigoPostal: "51101",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Hojancha" },
        { nombre: "Monte Romo" },
        { nombre: "Puerto Carrillo" },
        { nombre: "Huacas" },
      ],
    },
  ],

  // ========== PROVINCIA DE PUNTARENAS (6) ==========
  "6": [
    {
      nombre: "Puntarenas",
      codigoPostal: "60101",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Puntarenas" },
        { nombre: "Pitahaya" },
        { nombre: "Chomes" },
        { nombre: "Lepanto" },
        { nombre: "Paquera" },
        { nombre: "Manzanillo" },
        { nombre: "Guacimal" },
        { nombre: "Barranca" },
        { nombre: "Monte Verde" },
        { nombre: "Isla del Coco" },
        { nombre: "Cóbano" },
        { nombre: "Chacarita" },
        { nombre: "Chira" },
        { nombre: "Acapulco" },
      ],
    },
    {
      nombre: "Esparza",
      codigoPostal: "60201",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Espíritu Santo" },
        { nombre: "San Juan Grande" },
        { nombre: "Macacona" },
        { nombre: "San Rafael" },
        { nombre: "San Jerónimo" },
      ],
    },
    {
      nombre: "Buenos Aires",
      codigoPostal: "60301",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Buenos Aires" },
        { nombre: "Volcán" },
        { nombre: "Potrero Grande" },
        { nombre: "Boruca" },
        { nombre: "Pilas" },
        { nombre: "Colinas" },
        { nombre: "Chánguena" },
        { nombre: "Biolley" },
        { nombre: "Brunka" },
      ],
    },
    {
      nombre: "Montes de Oro",
      codigoPostal: "60401",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Miramar" },
        { nombre: "La Unión" },
        { nombre: "San Isidro" },
      ],
    },
    {
      nombre: "Osa",
      codigoPostal: "60501",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Puerto Cortés" },
        { nombre: "Palmar" },
        { nombre: "Sierpe" },
        { nombre: "Bahía Ballena" },
        { nombre: "Piedras Blancas" },
        { nombre: "Bahía Drake" },
      ],
    },
    {
      nombre: "Quepos",
      codigoPostal: "60601",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Quepos" },
        { nombre: "Savegre" },
        { nombre: "Naranjito" },
      ],
    },
    {
      nombre: "Golfito",
      codigoPostal: "60701",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Golfito" },
        { nombre: "Puerto Jiménez" },
        { nombre: "Guaycará" },
        { nombre: "Pavón" },
      ],
    },
    {
      nombre: "Coto Brus",
      codigoPostal: "60801",
      costoEnvio: 2500,
      distritos: [
        { nombre: "San Vito" },
        { nombre: "Sabalito" },
        { nombre: "Agua Buena" },
        { nombre: "Limoncito" },
        { nombre: "Pittier" },
      ],
    },
    {
      nombre: "Parrita",
      codigoPostal: "60901",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Parrita" },
      ],
    },
    {
      nombre: "Corredores",
      codigoPostal: "61001",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Corredor" },
        { nombre: "La Cuesta" },
        { nombre: "Paso Canoas" },
        { nombre: "Laurel" },
      ],
    },
    {
      nombre: "Garabito",
      codigoPostal: "61101",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Jacó" },
        { nombre: "Tárcoles" },
      ],
    },
  ],

  // ========== PROVINCIA DE LIMÓN (7) ==========
  "7": [
    {
      nombre: "Limón",
      codigoPostal: "70101",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Limón" },
        { nombre: "Valle La Estrella" },
        { nombre: "Río Blanco" },
        { nombre: "Matama" },
      ],
    },
    {
      nombre: "Pococí",
      codigoPostal: "70201",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Guápiles" },
        { nombre: "Jiménez" },
        { nombre: "Rita" },
        { nombre: "Roxana" },
        { nombre: "Cariari" },
        { nombre: "Colorado" },
        { nombre: "La Colonia" },
      ],
    },
    {
      nombre: "Siquirres",
      codigoPostal: "70301",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Siquirres" },
        { nombre: "Pacuarito" },
        { nombre: "Florida" },
        { nombre: "Germania" },
        { nombre: "El Cairo" },
        { nombre: "Alegría" },
      ],
    },
    {
      nombre: "Talamanca",
      codigoPostal: "70401",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Bratsi" },
        { nombre: "Sixaola" },
        { nombre: "Cahuita" },
        { nombre: "Telire" },
      ],
    },
    {
      nombre: "Matina",
      codigoPostal: "70501",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Matina" },
        { nombre: "Batán" },
        { nombre: "Carrandi" },
      ],
    },
    {
      nombre: "Guácimo",
      codigoPostal: "70601",
      costoEnvio: 2500,
      distritos: [
        { nombre: "Guácimo" },
        { nombre: "Mercedes" },
        { nombre: "Pocora" },
        { nombre: "Río Jiménez" },
        { nombre: "Duacarí" },
      ],
    },
  ],
} as const;

export type ProvinciaId = keyof typeof cantones;

