export const provincias = [
    { id: "1", nombre: "San José", iso: "SJ" },
    { id: "2", nombre: "Alajuela", iso: "A" },
    { id: "3", nombre: "Cartago", iso: "C" },
    { id: "4", nombre: "Heredia", iso: "H" },
    { id: "5", nombre: "Guanacaste", iso: "G" },
    { id: "6", nombre: "Puntarenas", iso: "P" },
    { id: "7", nombre: "Limón", iso: "L" },
  ];
  
  export const cantones = {
    "1": [
      { nombre: "San José", codigoPostal: "10101" },
      { nombre: "Escazú", codigoPostal: "10201" },
      { nombre: "Desamparados", codigoPostal: "10301" },
      { nombre: "Puriscal", codigoPostal: "10401" },
      { nombre: "Tibas", codigoPostal: "11301" },
      { nombre: "Moravia", codigoPostal: "11401" },
      { nombre: "Montes de Oca", codigoPostal: "11501" },
      { nombre: "Curridabat", codigoPostal: "11801" },
      { nombre: "Pérez Zeledón", codigoPostal: "11901" },
      { nombre: "San Isidro de El General", codigoPostal: "11902" },
      { nombre: "Aserrí", codigoPostal: "10601" },
      { nombre: "Alajuelita", codigoPostal: "11001" },
      { nombre: "San Miguel", codigoPostal: "11101" },
      { nombre: "Carmen", codigoPostal: "10102" },
      { nombre: "San Juan de Dios", codigoPostal: "10801" },
      { nombre: "Santa Teresa", codigoPostal: "10901" },
    ],
    "2": [
      { nombre: "Alajuela", codigoPostal: "20101" },
      { nombre: "San Ramón", codigoPostal: "20201" },
      { nombre: "Grecia", codigoPostal: "20301" },
      { nombre: "Naranjo", codigoPostal: "20601" },
      { nombre: "Palmares", codigoPostal: "20701" },
      { nombre: "Atenas", codigoPostal: "20501" },
      { nombre: "La Fortuna", codigoPostal: "21007" },
      { nombre: "Sarchí Norte", codigoPostal: "21201" },
      { nombre: "Sarchí Sur", codigoPostal: "21202" },
      { nombre: "Zarcero", codigoPostal: "21101" },
      { nombre: "Carrillos", codigoPostal: "20804" },
      { nombre: "Orotina", codigoPostal: "20901" },
      { nombre: "Los Chiles", codigoPostal: "21401" },
      { nombre: "San Carlos", codigoPostal: "21001" },
      { nombre: "Guatuso", codigoPostal: "21301" },
      { nombre: "Upala", codigoPostal: "21302" },
    ],
    "3": [
      { nombre: "Cartago", codigoPostal: "30101" },
      { nombre: "La Unión", codigoPostal: "30301" },
      { nombre: "Jiménez", codigoPostal: "30401" },
      { nombre: "Turrialba", codigoPostal: "30501" },
      { nombre: "Alvarado", codigoPostal: "30601" },
      { nombre: "El Guarco", codigoPostal: "30701" },
      { nombre: "Oreamuno", codigoPostal: "30801" },
      { nombre: "Paraíso", codigoPostal: "30201" },
    ],
    "4": [
      { nombre: "Heredia", codigoPostal: "40101" },
      { nombre: "Barva", codigoPostal: "40201" },
      { nombre: "Santo Domingo", codigoPostal: "40301" },
      { nombre: "Santa Bárbara", codigoPostal: "40401" },
      { nombre: "San Rafael", codigoPostal: "40501" },
      { nombre: "San Isidro", codigoPostal: "40601" },
      { nombre: "Belen", codigoPostal: "40701" },
      { nombre: "Flores", codigoPostal: "40801" },
      { nombre: "San Pablo", codigoPostal: "40901" },
      { nombre: "San Juan de Tibás", codigoPostal: "11302" },
    ],
    "5": [
      { nombre: "Liberia", codigoPostal: "50101" },
      { nombre: "Nicoya", codigoPostal: "50201" },
      { nombre: "Santa Cruz", codigoPostal: "50301" },
      { nombre: "Tilarán", codigoPostal: "50801" },
      { nombre: "Bagaces", codigoPostal: "50401" },
      { nombre: "Carrillo", codigoPostal: "50501" },
      { nombre: "La Cruz", codigoPostal: "51001" },
      { nombre: "Hojancha", codigoPostal: "51101" },
    ],
    "6": [
      { nombre: "Puntarenas", codigoPostal: "60101" },
      { nombre: "Esparza", codigoPostal: "60201" },
      { nombre: "Buenos Aires", codigoPostal: "60301" },
      { nombre: "Osa", codigoPostal: "60501" },
      { nombre: "Golfito", codigoPostal: "60701" },
      { nombre: "Coto Brus", codigoPostal: "60801" },
      { nombre: "Corredores", codigoPostal: "60601" },
      { nombre: "Parrita", codigoPostal: "60901" },
      { nombre: "Quepos", codigoPostal: "60601" },
    ],
    "7": [
      { nombre: "Limón", codigoPostal: "70101" },
      { nombre: "Pococí", codigoPostal: "70201" },
      { nombre: "Siquirres", codigoPostal: "70301" },
      { nombre: "Talamanca", codigoPostal: "70401" },
      { nombre: "Matina", codigoPostal: "70501" },
      { nombre: "Guácimo", codigoPostal: "70601" },
      { nombre: "Batán", codigoPostal: "70206" },
    ],
  } as const;
  
  export type ProvinciaId = keyof typeof cantones;